name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main # Or whichever branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Add any build steps here if your site needs building (e.g., npm run build)
      # - name: Install Dependencies and Build
      #   run: |
      #     npm install
      #     npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_WEBSITE_PAMIK }}'
          channelId: live
          projectId: portfolio-website-pamik